### ISSUE TITLE
Bower

### ISSUE THREAD

**Issue by jbrooksuk** [convergame/convergame-engine#10]
Make it Bower compatible, then you won't need to use submodules on your js13k entry ;)

**Comment by DivineOmega** [comment]
Certainly worth doing!

During the game jam we were constantly reworking the engine alongside the actual game, so using a git submodule in this particular instance was actually very convenient. When the engine is at a more stable state and have various modular components, I imagine Bower or something similar will be the recommended installation method.

**Comment by ojdon** [comment]
While I don't recommend it currently. You can install the Convergame engine via bower using: `bower install convergame`.

This will however, become recommended once the first release is considered stable. 

Closing.
