### ISSUE TITLE
Method renaming

### ISSUE THREAD

**Issue by jbrooksuk** [convergame/convergame-engine#14]
I don't know how important this is to you guys, but I was thinking of the following:

- `blankCanvas` becomes `fillCanvasWithColor`
- `ondragstart` becomes `onDragStart` to adhere to the camelCase used before
- `onselectstart` becomes `onSelectStart` to also adhere to the camelCase used before
- `fullscreen` becomes `enableFullscreen`
- `isCollide` becomes `isColliding` or perhaps `doObjectsCollide` - this would be good if each object was its own class, because you could add a method to it for `isCollidingWith` and only pass through the second object.

**Comment by ojdon** [comment]
Makes sense. I'll plan this in sometime.

**Comment by DivineOmega** [comment]
Aliasing the old method names to the new ones would make sense. I would say the old methods should be show 'This method is deprecated. Use method X instead.' in both comments and in `console.log` messages.

**Comment by jbrooksuk** [comment]
> in both comments

Ah yeah, I was going to document all of the methods as well.

**Comment by DivineOmega** [comment]
@jbrooksuk Discussion related to documentation can be found in #9. :)
