### ISSUE TITLE
Break into classes

### ISSUE THREAD

**Issue by jbrooksuk** [convergame/convergame-engine#16]
Having a class-based system would allow for inheritance, a more suited syntax and probably some cool features.

You'd at least need:

- Sprite
- Sound
  - Persistent (background audio)
  - Effect (walking, tools)
- Scene
  - Scenes themselves be able to be overlaid on top (#8) to create HUD's and then easily identify what it is you you're updating.

I'm missing some, I know. Please add.

**Comment by DivineOmega** [comment]
Agreed.

I feel persistent (background audio) could be handled by the same persistent scenes mechanism that would support creating rendered overlays (#8). Currently working on this idea. It could also be used to modularise the support of different controllers.

**Comment by ojdon** [comment]
[Done!](https://github.com/convergame/convergame-engine/pull/23)
