### ISSUE TITLE
Persistent storage Convergame component

### ISSUE THREAD

**Issue by DivineOmega** [convergame/convergame-engine#27]
We should abstract away various methods of persistent storage into an easy to use Convergame component. Initially, this could use HTML5 local storage, but could be expanded to use file writing via node.js or cloud based key-value store system.

Example methods:

* `Convergame.storage.set(key, value)`
* `Convergame.storage.get(key)`
* `Convergame.storage.configure(driver, options)` - Where `driver` is, for example, `localStorage` and `options` is an object containing various configurable options specific to the selected driver.

**Comment by ojdon** [comment]
Using HTML5 LocalStorage would be fine for the 0.1 release. Having additional drivers would be a useful feature, however would require a lot more work so would need to be considered for future releases of the Convergame engine.
