### ISSUE TITLE
Documentation!

### ISSUE THREAD

**Issue by DivineOmega** [convergame/convergame-engine#9]
Ideas for documentation topics:

* About Convergame
* Quick start guide
* Function reference

I think we should create a `docs` directory in the `covergame-engine` repo and do everything as Mark Down. This means the files can be read online (on GitHub) and people who download the Covergame package (as a submodule or zip) can read the docs offline too!

**Comment by ojdon** [comment]
I agree. Maybe use Jekyll to render the markdown files as HTML as well. :)

**Comment by jbrooksuk** [comment]
Or use Readme.io - those guys rock!

**Comment by DivineOmega** [comment]
Agreed, they do.

**Comment by ojdon** [comment]
Yeah. But I guess it's down to how important offline support is. Personally, I'm very rarely not able to connect online.

**Comment by ojdon** [comment]
Btw, the Convergame engine has a readme.io FOSS account approved. The url can be found [here](http://convergame.readme.io/v1.0). 

I'll start focusing on getting the documentation work going once a few areas of the engine have been refactored.

Closing.

**Comment by jbrooksuk** [comment]
:+1:
